Repository laminas/laminas.github.io, pull requests merged in 2020-01, with the labels that each got.

#5 Add popper.js to JS build
  asset/gulpfile.js
  js/scripts.js
Labels: Bug, Documentation

#7 Updates cards on overview
  index.html
Labels: Enhancement

#11 Fixes typo: Laminas
  index.html
Labels: Bug

#16 removed underline from cards on hover
  asset/sass/blocks/_card.scss
  build/build-component-lists.php
  components/index.html
  css/styles.css
  index.html
  mvc/index.html
Labels: Bug

#18 Updates styling of logos for hover status to show always all parts of the logos
  asset/sass/blocks/_card.scss
Labels: Bug

#19 Updates id attributes and order of numeration in migration docs
  migration/index.html
Labels: Bug

#20 Updates rendered CSS
  css/styles.css
Labels: Bug

#23 Fixes #21 - Disable AnchorJS on overviews
  asset/js/base.js
  asset/sass/blocks/_anchorjs.scss
  css/styles.css
  js/scripts.js
Labels: Bug

#25 Updates background colour for overviews and documentation pages
  asset/sass/_projects.scss
  asset/sass/_settings.scss
  asset/sass/blocks/_overview.scss
  asset/sass/styles.scss
  components/index.html
  css/styles.css
  index.html
  migration/faq/index.html
  migration/index.html
  mvc/index.html
Labels: Bug

#26 Adds language support for properties in the Gulp file
  asset/gulpfile.js
  js/scripts.js
Labels: Enhancement

#27 Updates styles for third headlines
  asset/sass/blocks/_content.scss
Labels: Enhancement

#28 Updates styles for title on overview
  asset/sass/blocks/_overview.scss
  css/styles.css
Labels: Bug

#29 Adds text decoration for links in content block for better visibility
  asset/sass/blocks/_content.scss
  css/styles.css
Labels: Bug
