Repository laminas/laminas.github.io, pull requests merged in 2020-03, with the labels that each got.

#55 Remove option installing laminas-migration as local dependency
  migration/index.html
Labels: Bug, Documentation

#51 Added documentation for the new `--keep-locked-versions`
  migration/index.html
Labels: Enhancement

#56 Added missing `of`
  migration/index.html
Labels: Bug, Documentation

#58 Adds missing end tag in code example for grep
  migration/faq/index.html
Labels: Bug

#59 Updates config file for GitHub pages to exclude build directory
  _config.yml
Labels: Bug

#62 Updates styling of headline of fourth order
  asset/sass/blocks/_content.scss
  asset/sass/blocks/_overview.scss
  css/styles.css
Labels: Bug

#64 Adds FAQ items about importing namespaces and 3rd party classes
  migration/faq/index.html
Labels: Documentation, Documentation Needed
